app/views/users.py
from flask import Blueprint, redirect, render_template, url_for, g, request
from datetime import datetime, timedelta
from ..auth import hash_password, login_required
from ..models import User, Session
from ..forms import UserForm, LoginForm, ProfileForm, EditUserForm
from ..users import copy_user_in_form, copy_form_in_user
from ..images import get_image, save_image
from ..main import db


bp = Blueprint('users', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        response = redirect(url_for('posts.index'))
        user = User.query.filter_by(
            username=form.username.data,
            password_hash=hash_password(form.username.data, form.password.data)
        ).one()
        user.last_login = datetime.utcnow()
        session = Session(user=user)
        
        db.session.add(user)
        db.session.add(session)
        db.session.commit()
        expires = datetime.utcnow() + timedelta(days=90)
        response.set_cookie('krusty-session', session.token, expires=expires)
        return response

    return render_template('users/login.html', form=form)


@bp.route('/edit_info', methods=['GET', 'POST'])
@login_required
def edit_info():
    form = EditUserForm()

    if form.validate_on_submit():
        user = User.query.filter_by(id=g.user.id).one()
        copy_form_in_user(form, user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('posts.index'))

    if request.method == 'GET':
        copy_user_in_form(g.user, form)

    return render_template('users/info.html', form=form, mode='edit')


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserForm()

    if form.validate_on_submit():
        user = User(is_enabled=True)
        copy_form_in_user(form, user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))

    return render_template('users/info.html', form=form, mode='signup')


@bp.route('/profile/<string:username>')
@login_required
def profile_of(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        return 'User not found', 404

    return render_template('users/profile.html', user=user, mode='view')


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    user = g.user
    form = ProfileForm()

    if form.validate_on_submit():
        if form.profile_image.data:
            user.profile_image_name = save_image(form.profile_image.data)

        if form.header_image.data:
            user.header_image_name = save_image(form.header_image.data)

        user.user_info = form.user_info.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('posts.index'))

    form.user_info.data = user.user_info

    return render_template('users/profile.html', user=user,
                           form=form, mode='edit')



    

@bp.route('/notifications')
@login_required
def notifications():
    return render_template('users/notifications.html')

app/templates/users/info.html
{% extends 'base.html' %} 
{% from 'shared/_form.html' import render_field %} 

{% block head %}
	<link type="text/css" rel="stylesheet" href="{{ asset_url('css/profile.css') }}" />
	<title>Profile of {{ form.username.data or 'New user' }} - Krusty Dank Meme</title>
{% endblock %} 

{% block header_title %} 
	{% if mode == 'edit' %}
		<span class="text">{{ _('Edit your profile') }}</span>
	{% elif mode == 'signup' %}
		<span class="text">{{ _('Sign up for a new account') }}</span>
	{% endif %} 
{% endblock %} 

{% block content %}
	<form method="post" enctype="multipart/form-data" class="user-info-editor">
		<div class="user-info">
			{% if mode == 'edit' %}
				<h1 class="title">{{ _('Edit your personal data') }}</h1>
			{% elif mode == 'signup' %}
				<h1 class="title">{{ _('Create your account') }}</h1>
			{% endif %}
			{{ form.csrf_token }} 
			{{ render_field(form.username) }} 
			{{ render_field(form.email) }} 
			{{ render_field(form.first_name) }} 
			{{ render_field(form.last_name) }}
			{{ render_field(form.password) }} 
			{{ render_field(form.password_confirm) }} 
			{{ render_field(form.address,) }} 
			{{ render_field(form.town) }} 
			{{ render_field(form.zip_code) }}
			{{ render_field(form.birthday) }} 
			{{ render_field(form.gender) }}
			{{ render_field(form.coins, readonly=True) }}
			{% if mode == 'edit' %} 
				{{ render_field(form.old_password) }}
			{% endif %}
			
				{% if mode == 'signup' %}
					<button type="submit" style="display: inline" class="button standalone">{{ _('Sign up') }}</button>
				{% elif mode == 'edit' %}
					<button type="submit" style="display: inline" class="button standalone">{{ _('Save') }}</button>
					<a href="{{ url_for('users.edit_profile') }}">{{ _('Edit your profile') }}</a>
				{% endif %}
		</div>
	</form>
{% endblock %} 

app/templates/users/login.html
{% extends 'base.html' %}
{% from 'shared/_form.html' import render_field %}

{% block head %}
	<link type="text/css" rel="stylesheet" href="{{ asset_url('css/login.css') }}" />
	<title>Login - Krusty Dank Meme</title>
{% endblock %}

{% block header_title %}
	<span class="text">Login</span>
{% endblock %}

{% block content %}
	<div class="background">
		<div class="login-window">
			<form id="login-form" method="post">
				{{ form.csrf_token }}
				{{ render_field(form.username) }}
				{{ render_field(form.password) }}
				<button type="submit" class="button standalone">Login</button>
			</form>
		</div>
	</div>
{% endblock %}

app/templates/users/notifications.html
{% extends 'base.html' %}

{% block head %}
    <title>{{ g.user.notification_amount }} {{ _('Notifications') }}</title>
    <link rel="stylesheet" href="{{ asset_url('css/notifications.css') }}">
{% endblock %}

{% block async_scripts %}
	<script async="async" src="{{ asset_url('js/notifications.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="notification-list">
        {% for n in g.user.notifications %}
            <div class="notification {{ 'read' if n.is_read }}" data-nid="{{ n.id }}">
                <span class="datetime">{{ n.added | date_s }}</span>
                <span class="text">{{ n.text }}</span>
                <div class="frame">
                    {% if n.is_read %}
                        <span class="icon img-checked"></span>
                    {% else %}
                        <span class="icon img-unchecked"></span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}


{% block scripts %}
    <script>
        window.whenApp(app => {
            document.querySelectorAll(".notification-list .notification").forEach(function(el) {
                initNotification(app, el);
            });
        });
    </script>
{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}
{% from 'shared/_form.html' import render_field %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{{ asset_url('css/post.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset_url('css/profile.css') }}">
	<title>Profile of {{ user.username }} - Krusty dank meme</title>
{% endblock %}

{% block async_scripts %}
    <script async="async" src="{{ asset_url('js/image-picker.js') }}"></script>
    <script async="async" src="{{ asset_url('js/profile.js') }}"></script>
{% endblock %}

{% block content %}
	<form class="profile" method="POST" data-userid="{{ user.id }}" data-editable="{{ (mode == 'edit') | int }}">
		<div class="header-image" 
			{% if user.header_image_url %}
				style="background-image: url({{ user.header_image_url }})" 
			{% endif %}>
		</div> 
		<div class="profile-image-container">
			<div class="background">
				<div class="profile-image img-placeholder"
				{% if user.profile_image_url %}
					style="background-image: url({{ user.profile_image_url }})"
				{% endif %}></div>
			</div>
		</div>
		<div class="content-wrapper">
			<div class="username center">
				<span class="text">{{ user.username }}</span>
			</div>
			<div class="user-stat-container">
				<div class="user-stat follower-amount">
					<div class="text strong center">Followers</div>
					<div class="text center amount">{{ user.follower_amount }}</div>
				</div>
				<div class="user-stat total-like-amount">
					<div class="text strong center">Total likes</div>
					<div class="text center amount">{{ user.total_like_amount }}</div>
				</div>
				<div class="user-stat total-post-amount">
					<div class="text strong center">
						<a class="no-decoration" href="{{ url_for('posts.index') }}#user{{ user.username }}">{{ _('Posts') }}</a>
					</div>
					<div class="text center amount">{{ user.post_amount }}</div>
				</div>
			</div>
			<div class="clear"></div>
			{% if mode == 'view' %}
				<div class="user-info">{{ user.user_info }}</div>
			{% elif mode == 'edit' %}
				{{ form.csrf_token }}
				{{ render_field(form.user_info) }}
				{{ form.header_image(class_='header-image-input') }}
				{{ form.profile_image(class_='profile-image-input') }}
			{% endif %}
			{% if mode == 'view' and g.user.id != user.id %}
				<button class="button subscribe-button {{ 'active' if user.is_subscribed }}" type="button">
					<span class="text">{{ _('Subscribe') }}</span>
					{% if user.is_subscribed %}
						<span class="icon img-checked"></span>
					{% else %}
						<span class="icon img-unchecked"></span>
					{% endif %}
				</button>
			{% elif mode == 'edit' %}
				<button class="button standalone" type="submit">{{ _('Save') }}</button>
			{% endif %}
		</div>
	</form>
{% endblock %}

{% block scripts %}
    <script>
        window.whenApp(function(app) {
            initProfile(app, document.querySelector(".profile"));
        });
    </script>
{% endblock %}