app/views/posts.py
from flask import Blueprint, redirect, render_template, url_for, \
     current_app, g, request
from datetime import datetime
from flask_babel import _
from ..auth import login_required, moderator_required
from ..models import Post, Hashtag
from ..images import get_image
from ..tags import get_tags
from ..main import db



bp = Blueprint('posts', __name__)


@bp.route('/')
@login_required
def index():
    return render_template('posts/index.html', 
        posts=Post.query.filter(Post.approved != None)
			.order_by(Post.approved.desc()).limit(2),
        feed='all', title='Posts'
    )


@bp.route('/approve')
@login_required
def approve():
    assert g.user.is_admin or g.user.is_moderator
    return render_template('posts/index.html', 
        posts=Post.query.filter(Post.approved == None)
			.order_by(Post.added.desc()).limit(2),
        feed='approve', title=_('Approve')
    )


@bp.route('/yours')
@login_required
def yours():
    return render_template('posts/index.html', 
        posts=Post.query.filter_by(author_id=g.user.id)
			.order_by(Post.added.desc()).limit(2),
        feed='yours', title=_('Your posts')
    )


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def new(): 
    return render_template('posts/editor.html')


@bp.route('/edit/<int:post_id>')
@login_required
def edit(post_id):
    post = Post.query.filter_by(id=post_id).one()
    return render_template('posts/editor.html', post=post)

app/templates/posts/_macros.html
{% macro post(p, mode) %}
	<div class="post" data-postid="{{ p.id }}">
		<div class="background">
			<div class="image" style="background-image: url({{ p.image_url }})"></div>
		</div>
		<div class="post-details">
			<div class="wrapper">
				<div class="post-reactions">
					<div class="button-group pull-right">
						<button class="button like-button {{ 'active' if p.is_liked }}">
							<span class="amount">{{ p.like_amount }}</span>
							<span class="icon img-like"></span>
						</button>
						<button class="button comment-button">
							<span class="amount">{{ p.comment_amount }}</span>
							<span class="icon img-comment"></span>
						</button>
						{% if p.is_editable %}
							<a class="button" href="{{ p.edit_url }}">
								<span class="icon img-pencil"></span>
							</a>
							<button class="button delete-button">
								<span class="icon img-trashbin"></span>
							</button>
						{% endif %}
						{% if mode == 'approve' %}
							<button class="button approve-button">
								{% if p.is_approved %}
									<span class="icon img-checked"></span>
								{% else %}
									<span class="icon img-unchecked"></span>
								{% endif %}
							</button>
						{% endif %}
					</div>
				</div>
				<div class="post-autor">
					<a class="strong no-decoration" href="{{ p.author.profile_url }}">
						{{ p.author.username }}
					</a>
					{% if mode == 'yours' %}
						<span class="text">{{ _('[Approved]') if p.approved else _('[Not approved]') }}</span>
					{% endif %}
				</div>
				<div class="clear"></div>
				<div class="post-text">
					<span class="text">{{ p.text }}</span>
				</div>
				<div class="comment-area">
					<form class="new-comment-form" method="post">
						<div class="input-group">
							<button type="submit" class="new-comment-submit button pull-right form-addon" disabled="disabled">Post</button>
							<input type="text" class="new-comment-input form-control" placeholder="{{ _('Add a comment') }}" name="new-comment-text">
						</div>
					</form>
					<div class="comment-list">
						{% for c in p.comments %}
							{{ comment(c) }}
						{% endfor %}
					</div>
				</div>
			</div>
			<div class="toggle-comment-area-button img-arrow-down"></div>
		</div>
	</div>
{% endmacro %}

{% macro comment(c) %}
	<div class="comment" data-commentid="{{ c.id }}">
		<button class="button like-comment pull-right {{ 'active' if c.is_liked }}">
			<span class="amount">{{ c.like_amount }}</span>
			<span class="icon img-like"></span>
		</button>
		<a class="comment-author strong no-decoration" href="{{ c.author.profile_url }}">
			{{ c.author.username }}
		</a>
		<div class="comment-text">{{ c.text }}</div>
	</div>
{% endmacro %}

app/templates/posts/editor.html
{% extends 'base.html' %}


{% block head %}
	<link type="text/css" rel="stylesheet" href="{{ asset_url('css/post.css') }}" />
	<title>{{ _('Edit post') if post else _('New post') }} - Krusty Dank Meme</title>
{% endblock %}

{% block async_scripts %}
    <script async="async" src="{{ asset_url('js/post-editor.js') }}"></script>
    <script async="async" src="{{ asset_url('js/image-picker.js') }}"></script>
{% endblock %}


{% block content %}
	<form method="post" class="post-editor" id="upload-form">
		<div class="post-list">
			<div class="post" data-postid="{{ post.id if post else 0 }}">
				<div class="background">
					{% if not post %}
						<div class="image img-placeholder image-preview"></div>
					{% else %}
						<div class="image image-preview" style="background-image: url({{ post.image_url }})"></div>
					{% endif %}
				</div>
				<div class="post-details">
					<div class="progress-bar hidden">
						<div class="slider"></div>
					</div>
					<div class="input-group">
						<textarea class="form-control text-input" name="text">{{ post.text if post }}</textarea>
						{% if not post %}
							<button id="submit-button" class="button pull-right form-addon submit-button" disabled="disabled" type="submit">{{ _('Save') }}</button>
						{% else %}
							<button id="submit-button" class="button pull-right form-addon submit-button" type="submit">{{ _('Save') }}</button>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</form>
{% endblock %}

{% block scripts %}
    <script>
        window.whenApp(function(app) {
            initPostEditor(app, document.querySelector("#upload-form"), {
                onSave: function() {window.location.href = "{{ url_for('posts.index') }}"}
            });
        });
    </script>
{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}
{% from 'posts/_macros.html' import post %}


{% block head %}
	<link type="text/css" rel="stylesheet" href="{{ asset_url('css/post.css') }}" />
	<title>{{ title }} - Krusty Dank Meme</title>
{% endblock %}

{% block async_scripts %}
    <script async="async" src="{{ asset_url('js/posts.js') }}"></script>
{% endblock %}


{% block header_title %}
	<span class="text">{{ title }}</span>
{% endblock %}

{% block content %}
	<div class="post-list">
		{% for p in posts %}
			{{ post(p, feed) }}
		{% endfor %}
	</div>
    <button style="margin-top: 50px" class="button center-block" id="fetch-button">Fetch more</button>
{% endblock %}

{% block scripts %}
    <script>
        window.whenApp(function(app) {
            const plEl = document.querySelector("div.post-list");
            const fbEl = document.querySelector("#fetch-button");
            
            window.initPostList(app, plEl, {
                feed: "{{ feed }}",
                fetchButton: fbEl
            });
        });
    </script>
{% endblock %}